/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "@creditkarma/thrift-server-core";
export interface IDemoServiceException {
    message: string;
}
export interface IDemoServiceExceptionArgs {
    message: string;
}
export const DemoServiceExceptionCodec: thrift.IStructCodec<IDemoServiceExceptionArgs, IDemoServiceException> = {
    encode(args: IDemoServiceExceptionArgs, output: thrift.TProtocol): void {
        const obj: any = {
            message: args.message
        };
        output.writeStructBegin("DemoServiceException");
        if (obj.message != null) {
            output.writeFieldBegin("message", thrift.TType.STRING, 1);
            output.writeString(obj.message);
            output.writeFieldEnd();
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[message] is unset!");
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    },
    decode(input: thrift.TProtocol): IDemoServiceException {
        let _args: any = {};
        input.readStructBegin();
        while (true) {
            const ret: thrift.IThriftField = input.readFieldBegin();
            const fieldType: thrift.TType = ret.fieldType;
            const fieldId: number = ret.fieldId;
            if (fieldType === thrift.TType.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.TType.STRING) {
                        const value_1: string = input.readString();
                        _args.message = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.message !== undefined) {
            return {
                message: _args.message
            };
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Unable to read DemoServiceException from input");
        }
    }
};
export class DemoServiceException extends thrift.StructLike implements IDemoServiceException {
    public message: string;
    public readonly _annotations: thrift.IThriftAnnotations = {};
    public readonly _fieldAnnotations: thrift.IFieldAnnotations = {};
    constructor(args: IDemoServiceExceptionArgs) {
        super();
        if (args.message != null) {
            const value_2: string = args.message;
            this.message = value_2;
        }
        else {
            throw new thrift.TProtocolException(thrift.TProtocolExceptionType.UNKNOWN, "Required field[message] is unset!");
        }
    }
    public static read(input: thrift.TProtocol): DemoServiceException {
        return new DemoServiceException(DemoServiceExceptionCodec.decode(input));
    }
    public static write(args: IDemoServiceExceptionArgs, output: thrift.TProtocol): void {
        return DemoServiceExceptionCodec.encode(args, output);
    }
    public write(output: thrift.TProtocol): void {
        return DemoServiceExceptionCodec.encode(this, output);
    }
}
